### ISSUE TITLE
Automatic adjustment for ratio between Staked and Available Tokens.

### ISSUE THREAD

**Issue by DylanNNT** [NekoHitDev/ritmin-frontend#20]
The staking calculator should make automatic updates, depending on the amount of tokens the Creator wants to sell for the project. If the estimated costs for setting parameters can be shown during the project creation phase, it will help the Creator submit a more realistic project proposal.

I believe I chose 100 CAT can be bought, and I needed to stake 1 CAT. When I went to stake the project, it was asking for 1,250 CAT. 

The math is hard for the user to do on the front-end, and the platform should do it for the user.

**Comment by hurui200320** [comment]
The frontend can be improved. The stake rate is a little bit confusing and I saw similar things happen a few days ago. By design, the stake rate describes how many tokens you want to stake for each token you sell, normally it's 0.5 or something smaller than 1. But some users might treat it as a percentage or something, and give a really large number. I think adding a stake calculator will help a lot.

I'll transfer this issue to the frontend repo.

**Comment by ykoitzsch** [comment]
I think its instead of showing the stakePerToken value, we should display the actual stakedAmount. This will be easier to understand for the users.
So if there are 1_000_000 staked tokens and the stakePerToken value is 0,5, then we display 500_000.

**Comment by ykoitzsch** [comment]
In the new frontend, the user receives an immediate update on how many tokens he will have to stake once the project has been created.
